version: 2
updates:
  - package-ecosystem: maven
    directory: /init
    schedule:
      interval: monthly
    groups:
      init-dependencies:
        patterns: ['*']
  - package-ecosystem: maven
    directory: /web
    schedule:
      interval: monthly
    groups:
      web-dependencies:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
